WITH MONTHLY_RENTALS as (
    select CAR_ID, MONTH(START_DATE) as MONTH, count(*) as RECORDS
    from CAR_RENTAL_COMPANY_RENTAL_HISTORY
    where START_DATE between '2022-08-01' and '2022-10-31'
    group by CAR_ID, MONTH(START_DATE)
)

select M.MONTH, M.CAR_ID, M.RECORDS
from MONTHLY_RENTALS M
WHERE M.CAR_ID IN (
    -- 전체 기간 동안 총 대여 횟수가 5회 이상인 자동차 찾기
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
order by M.MONTH ASC, M.CAR_ID DESC